### ISSUE TITLE
如何在基于三期处理器的星空板上使用C程序直接控制更多外设？

### ISSUE THREAD

**Issue by zhengpushi** [oscc-web/ysyx-website#1]
在星空板卡v1.2上设计了很多外设：LED, KEY, VGA, 等，这些外设应该可以由FPGA核心板来访问。根据一生一芯RISCV处理器（以下简称CPU）的架构，以及Chiplink的设计，这些外设应该可以由CPU直接访问，是吗？
换言之，这些外设的地址是多少？如何写C程序来访问这些外设？
以UART为例，它是标准的16550接口，我们只需要在汇编或C程序中访问地址 `0x1000_0000~0x1000_0006`,根据芯片手册即可操控。
那么，是否可以访问某个地址来控制LED,KEY,VGA等外设呢？

**Comment by maksyuki** [comment]
这个是需要通过ChipLink外设来访问，三期的地址空间如下：
## 地址空间分配

| 设备 | 地址空间 |
| --- | --- |
| reserve           | `0x0000_0000~0x01ff_ffff`|
| CLINT             | `0x0200_0000~0x0200_ffff`|
| reserve           | `0x0201_0000~0x0fff_ffff`|
| UART16550         | `0x1000_0000~0x1000_0fff`|
| SPI控制器         | `0x1000_1000~0x1000_1fff`|
| reserve           | `0x1000_2000~0x2fff_ffff`|
| SPI-flash XIP模式 | `0x3000_0000~0x3fff_ffff`|
| ChipLink MMIO     | `0x4000_0000~0x7fff_ffff`|
| memory            | `0x8000_0000~0xffff_ffff`|

然后让具体外设的的访问地址落在ChipLink MMIO地址范围内

**Comment by zhengpushi** [comment]
请问，ChipLink MMIO的是如何映射具体外设的？ 比如LED和KEY？ 是否还需要用户来开发FPGA上的程序才能访问这些外设呢

**Comment by maksyuki** [comment]
如何映射LED和KEY地址同学们自己自定义即可，需要开发FPGA上程序
