### ISSUE TITLE
上电复位后能成功启动，但hlep命令概率性跑飞 

### ISSUE THREAD

**Issue by wujw20** [oscc-web/ysyx-website#2]
频率调到25MHZ时依然出现这个问题，请问是否有手段可以定位问题所在？

**Comment by maksyuki** [comment]
这个很有可能是频率的问题，一种解决方法是选用更低频率的晶振，第二种是上电等待一段时间，让SoC芯片的温度上升，然后再复位。

**Comment by wujw20** [comment]
升温时序不是会变更差吗？

**Comment by maksyuki** [comment]
其实等一段时间复位是给FPGA核心板使用的
